name: Build Flutter iOS App

on:
  push:
    branches:
      - main  # Trigger build on push to the main branch
  pull_request:
    branches:
      - main  # Trigger build on pull request to main branch

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner to build iOS apps

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'  # Specify your Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build the app
      run: flutter build ios --release --no-codesign  # Build iOS release without signing

    - name: Create IPA
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Debug archive -archivePath ${{ github.workspace }}/Runner.xcarchive
        xcodebuild -exportArchive -archivePath ${{ github.workspace }}/Runner.xcarchive -exportOptionsPlist ${{ github.workspace }}/ios/Runner/ExportOptions.plist -exportPath ${{ github.workspace }}/build/ios/ipa
