name: Build Flutter iOS App Without Storyboards

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS builds

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'

    - name: Install dependencies
      run: flutter pub get

    - name: Build the app
      run: |
        flutter build ios --release --no-codesign
        cd ios
        # Create an archive using xcodebuild
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release archive -archivePath ${{ github.workspace }}/Runner.xcarchive
        # Export the IPA file
        xcodebuild -exportArchive -archivePath ${{ github.workspace }}/Runner.xcarchive -exportOptionsPlist ${{ github.workspace }}/ios/Runner/ExportOptions.plist -exportPath ${{ github.workspace }}/build/ios/ipa
