name: Build Flutter iOS App Without Storyboards

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS builds

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'  # Use the appropriate Flutter version

    - name: Install dependencies
      run: flutter pub get  # Install Flutter dependencies

    - name: Build the app
      run: |
        flutter build ios --no-codesign  # Build the iOS app without signing
        # The IPA will be located at build/ios/iphoneos/Runner.ipa
        ls -lh build/ios/iphoneos/  # List files to ensure IPA is created

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: ios-release
        path: build/ios/iphoneos/*.ipa  # Upload the IPA file for further use
